### ISSUE TITLE
代码编译不过exe4j找不到，程序运行保存连接的时候提示sqlexception

### ISSUE THREAD

**Issue by QADai** [peterchenhdu/td-genie#2]
请问有编译部署吗？或者有什么特殊配置让程序正常运行呢？

**Comment by QADai** [comment]
四月 24, 2024 9:55:29 上午 io.datafx.core.ExceptionHandler lambda$getLoggerListener$0
严重: DataFX Exception Handler
io.datafx.controller.flow.FlowException: java.lang.IllegalStateException: Cannot call Method: private void com.gitee.dbquery.tdgenie.gui.MainController.saveConnection() throws java.sql.SQLException
	at io.datafx.controller.flow.action.FlowMethodAction.handle(FlowMethodAction.java:69)
	at io.datafx.controller.flow.FlowHandler.handle(FlowHandler.java:237)
	at io.datafx.controller.flow.FlowHandler.handle(FlowHandler.java:169)
	at io.datafx.controller.flow.FlowHandler.handleActionWithExceptionHandler(FlowHandler.java:318)
	at io.datafx.controller.flow.FlowHandler.lambda$attachEventHandler$5(FlowHandler.java:301)
	at io.datafx.controller.util.ActionUtil.lambda$defineNodeAction$21(ActionUtil.java:23)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8411)

Caused by: java.lang.IllegalStateException: Cannot call Method: private void com.gitee.dbquery.tdgenie.gui.MainController.saveConnection() throws java.sql.SQLException
	at io.datafx.core.DataFXUtils$3.run(DataFXUtils.java:100)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.datafx.core.DataFXUtils.callPrivileged(DataFXUtils.java:92)
	at io.datafx.controller.flow.action.FlowMethodAction.handle(FlowMethodAction.java:66)
	... 68 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.datafx.core.DataFXUtils$3.run(DataFXUtils.java:98)
	... 71 more
Caused by: cn.hutool.http.HttpException: Unexpected end of file from server
	at cn.hutool.http.HttpResponse.init(HttpResponse.java:406)
	at cn.hutool.http.HttpResponse.initWithDisconnect(HttpResponse.java:379)
	at cn.hutool.http.HttpResponse.<init>(HttpResponse.java:76)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:976)
	at cn.hutool.http.HttpRequest.execute(HttpRequest.java:940)
	at com.gitee.dbquery.tdgenie.sdk.util.RestConnectionUtils.executeSql(RestConnectionUtils.java:58)
	at com.gitee.dbquery.tdgenie.sdk.util.RestConnectionUtils.getServerVersion(RestConnectionUtils.java:50)
	at com.gitee.dbquery.tdgenie.gui.MainController.saveConnection(MainController.java:615)
	... 76 more
Caused by: java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at cn.hutool.http.HttpConnection.responseCode(HttpConnection.java:472)
	at cn.hutool.http.HttpResponse.init(HttpResponse.java:403)
	... 83 more
